public class Main {
	public static void main(String[] args) {
		// CircularLinkedList list = new CircularLinkedList();
		Deque list = new Deque();
		// System.out.println(list.isEmpty());
		// list.enqueue(2);
		System.out.println(list.showNodes());
		list.insertBack(43);
		list.insertBack(253);
		System.out.println(list.showNodes());
		list.showNodes();
		list.insertBack(3);
		list.insertBack(53);
		System.out.println(list.showNodes());
		list.insertBack(153);
		list.insertBack(353);
		list.showNodes();
		System.out.println(list.showNodes());
		list.removeBack();
		list.removeBack();
		list.removeBack();
		list.removeBack();
		list.removeBack();
		list.insertBack(6);
		System.out.println(list.showNodes());
		// list.deleteNode(43);
		// System.out.println(list.showNodes());
		// list.deleteNode(53);
		// System.out.println(list.showNodes());
		// list.addToEnd(253);
		// list.showNodes();
		// list.addToEnd(253);
		// list.deleteNode(53);
		// list.showNodes();
		// list.deleteNode(53);
		// list.deleteNode(4);
		// list.showNodes();
		// list.deleteNode(2);
		// list.showNodes();
		// list.deleteNode(42);
		// list.showNodes();
		// list.deleteNode(3);
		// list.showNodes();
		// list.deleteNode(10);
		// list.showNodes();
		// list.deleteNode(253);
		// list.deleteNode(253);
		//// list.deleteNode(43);
		// list.showNodes();
		// System.out.println(list.find(2));
		// System.out.println(list.getHead());
		// System.out.println(list.getTail());
	}
}